version: '3.8'

services:

  php:
    build: ./php
    container_name: php
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9003
    ports:
      # host: port:container port
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mariadb:10.3.39
    container_name: db
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: suitecrm

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  elasticsearch:
    image: elasticsearch:5.6-alpine
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  data:
    driver: local